# Generated by Django 3.2.15 on 2022-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('rate_us', models.IntegerField()),
            ],
        ),
    ]
