# Generated by Django 3.2.15 on 2022-10-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20220924_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
