# Generated by Django 3.2.15 on 2022-10-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20221017_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='address',
            new_name='location',
        ),
    ]
