# Generated by Django 3.2.15 on 2022-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mycar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=60)),
                ('model_Name', models.CharField(max_length=60)),
                ('vehicle_number', models.CharField(max_length=60)),
                ('year_Of_Model', models.IntegerField(null=True)),
                ('fuel_Type', models.CharField(max_length=20)),
                ('mobile_number', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
    ]
