# Generated by Django 3.2.15 on 2022-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contanctpage',
            name='mobileNumber',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
