# Generated by Django 3.2.15 on 2022-09-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutpage',
            new_name='contanctpage',
        ),
    ]
