# Generated by Django 3.2.15 on 2022-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='basic',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='premium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='standard',
            field=models.IntegerField(null=True),
        ),
    ]
